// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qfkgvufaytcpmsjfsnhg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFma2d2dWZheXRjcG1zamZzbmhnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc4MDI1MTQsImV4cCI6MjA2MzM3ODUxNH0.LxNbqFySs1sQNtEO5YeST_D-e_bxYju7BC6_gkWSjkc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);